'use server'

/**
 * projects.ts — Server Actions for Project CRUD.
 *
 * Pattern: verifySession -> validate with Zod -> mutate DB -> writeAuditLog -> revalidate
 *
 * Key behaviours:
 *   - All optional empty-string fields are coerced to null before DB insert/update.
 *   - attendance_clocks are managed via replace-all pattern on update:
 *     DELETE all existing clocks for the project, then INSERT the new set.
 *   - project_number is auto-generated by DB trigger (PR26XXXXXX format).
 *     Client sends '' — trigger fills in the value on INSERT.
 *   - Soft-delete uses SECURITY DEFINER RPC soft_delete_projects() — same
 *     pattern as employees, bypasses RLS on deleted_at column.
 *   - Every mutation writes an immutable audit log entry.
 *   - Boolean fields from FormData arrive as 'true'/'false' strings or 'on'
 *     (checkbox) — all are normalised to boolean before Zod parse.
 */

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { verifySession } from '@/lib/dal'
import { writeAuditLog } from '@/lib/audit'
import { ProjectSchema } from '@/lib/schemas'

// ---------------------------------------------------------------------------
// Shared return type (matches employees.ts pattern)
// ---------------------------------------------------------------------------
type ActionState = {
  success: boolean
  error?: Record<string, string[]>
} | null

// ---------------------------------------------------------------------------
// Helper: normalise boolean FormData values
// ---------------------------------------------------------------------------
/**
 * formDataToBoolean — convert FormData string values to boolean.
 * Handles 'true'/'false' strings (from hidden inputs) and 'on' (checkboxes).
 * Defaults to the provided fallback if the value is absent.
 */
function formDataToBoolean(value: FormDataEntryValue | null, fallback = false): boolean {
  if (value === null || value === undefined) return fallback
  if (value === 'true' || value === 'on') return true
  if (value === 'false') return false
  return fallback
}

// ---------------------------------------------------------------------------
// Helper: coerce empty string to null for optional DB text columns
// ---------------------------------------------------------------------------
function nullIfEmpty(value: string | null | undefined): string | null {
  if (!value || value.trim() === '') return null
  return value.trim()
}

// ---------------------------------------------------------------------------
// createProject
// ---------------------------------------------------------------------------
export async function createProject(
  prevState: ActionState,
  formData: FormData
): Promise<ActionState> {
  const session = await verifySession()
  const supabase = await createClient()

  // Extract attendance_clocks JSON separately — not part of ProjectSchema fields
  const clocksJson = formData.get('attendance_clocks') as string | null

  // Build raw data from FormData — process booleans before Zod parse
  const rawData = Object.fromEntries(formData)
  delete rawData['attendance_clocks']

  // Normalise boolean fields (FormData sends strings; Zod expects boolean)
  const processedData = {
    ...rawData,
    pm_notifications:          formDataToBoolean(formData.get('pm_notifications'), true),
    sm_notifications:          formDataToBoolean(formData.get('sm_notifications'), true),
    cvc_is_employee:           formDataToBoolean(formData.get('cvc_is_employee'), true),
    supervision_notifications:  formDataToBoolean(formData.get('supervision_notifications'), false),
    supervision_attach_reports: formDataToBoolean(formData.get('supervision_attach_reports'), false),
  }

  // Validate with Zod
  const parsed = ProjectSchema.safeParse(processedData)
  if (!parsed.success) {
    return { success: false, error: parsed.error.flatten().fieldErrors }
  }

  const input = parsed.data

  // Insert project — project_number = '' triggers PR26XXXXXX auto-generation
  const { data, error } = await supabase
    .from('projects')
    .insert({
      name:           input.name,
      project_number: '',  // DB trigger fills this in
      open_date:      nullIfEmpty(input.open_date),
      expense_number: nullIfEmpty(input.expense_number),
      description:    nullIfEmpty(input.description),
      project_type:   input.project_type ?? null,
      status:         input.status,

      // PM
      project_manager_id: nullIfEmpty(input.project_manager_id),
      pm_email:           nullIfEmpty(input.pm_email),
      pm_phone:           nullIfEmpty(input.pm_phone),
      pm_notifications:   input.pm_notifications,

      // SM
      site_manager_id:  nullIfEmpty(input.site_manager_id),
      sm_email:         nullIfEmpty(input.sm_email),
      sm_phone:         nullIfEmpty(input.sm_phone),
      sm_notifications: input.sm_notifications,

      // CVC
      camp_vehicle_coordinator_id: nullIfEmpty(input.camp_vehicle_coordinator_id),
      cvc_is_employee:             input.cvc_is_employee,
      cvc_phone:                   nullIfEmpty(input.cvc_phone),

      // Client
      client_name:     nullIfEmpty(input.client_name),
      client_logo_url: nullIfEmpty(input.client_logo_url),

      // Supervision
      supervision_company:        nullIfEmpty(input.supervision_company),
      supervision_contact:        nullIfEmpty(input.supervision_contact),
      supervision_email:          nullIfEmpty(input.supervision_email),
      supervision_phone:          nullIfEmpty(input.supervision_phone),
      supervision_notifications:  input.supervision_notifications,
      supervision_attach_reports: input.supervision_attach_reports,

      // Location
      latitude:  input.latitude  ?? null,
      longitude: input.longitude ?? null,
      radius:    input.radius,

      created_by: session.userId,
    })
    .select()
    .single()

  if (error) {
    console.error('[createProject] DB error:', error.message)
    return { success: false, error: { _form: [error.message] } }
  }

  // Insert attendance_clocks — parse JSON array of clock ID strings
  if (clocksJson) {
    try {
      const clockIds: string[] = JSON.parse(clocksJson)
      const validClockIds = clockIds.filter((id) => id && id.trim() !== '')

      if (validClockIds.length > 0) {
        const clockRows = validClockIds.map((clockId) => ({
          project_id: data.id,
          clock_id:   clockId.trim(),
          created_by: session.userId,
        }))

        const { error: clockError } = await supabase
          .from('attendance_clocks')
          .insert(clockRows)

        if (clockError) {
          console.error('[createProject] Failed to insert attendance clocks:', clockError.message)
        }
      }
    } catch {
      console.error('[createProject] Invalid attendance_clocks JSON — skipped')
    }
  }

  // Write audit log (fire-and-forget)
  await writeAuditLog({
    userId:     session.userId,
    action:     'INSERT',
    entityType: 'projects',
    entityId:   data.id,
    oldData:    null,
    newData:    data as Record<string, unknown>,
  })

  revalidatePath('/admin/projects')
  return { success: true }
}

// ---------------------------------------------------------------------------
// updateProject
// ---------------------------------------------------------------------------
export async function updateProject(
  prevState: ActionState,
  formData: FormData
): Promise<ActionState> {
  const session = await verifySession()
  const supabase = await createClient()

  // Extract project id and attendance_clocks separately
  const projectId = formData.get('id') as string | null
  if (!projectId) {
    return { success: false, error: { _form: ['מזהה פרויקט חסר'] } }
  }

  const clocksJson = formData.get('attendance_clocks') as string | null

  // Build raw data from FormData — process booleans
  const rawData = Object.fromEntries(formData)
  delete rawData['id']
  delete rawData['attendance_clocks']

  const processedData = {
    ...rawData,
    pm_notifications:           formDataToBoolean(formData.get('pm_notifications'), true),
    sm_notifications:           formDataToBoolean(formData.get('sm_notifications'), true),
    cvc_is_employee:            formDataToBoolean(formData.get('cvc_is_employee'), true),
    supervision_notifications:  formDataToBoolean(formData.get('supervision_notifications'), false),
    supervision_attach_reports: formDataToBoolean(formData.get('supervision_attach_reports'), false),
  }

  // Validate
  const parsed = ProjectSchema.safeParse(processedData)
  if (!parsed.success) {
    return { success: false, error: parsed.error.flatten().fieldErrors }
  }

  const input = parsed.data

  // Fetch old data for audit log (also verifies row exists)
  const { data: oldData } = await supabase
    .from('projects')
    .select('*')
    .eq('id', projectId)
    .single()

  // Update project record
  const { data, error } = await supabase
    .from('projects')
    .update({
      name:           input.name,
      open_date:      nullIfEmpty(input.open_date),
      expense_number: nullIfEmpty(input.expense_number),
      description:    nullIfEmpty(input.description),
      project_type:   input.project_type ?? null,
      status:         input.status,

      // PM
      project_manager_id: nullIfEmpty(input.project_manager_id),
      pm_email:           nullIfEmpty(input.pm_email),
      pm_phone:           nullIfEmpty(input.pm_phone),
      pm_notifications:   input.pm_notifications,

      // SM
      site_manager_id:  nullIfEmpty(input.site_manager_id),
      sm_email:         nullIfEmpty(input.sm_email),
      sm_phone:         nullIfEmpty(input.sm_phone),
      sm_notifications: input.sm_notifications,

      // CVC
      camp_vehicle_coordinator_id: nullIfEmpty(input.camp_vehicle_coordinator_id),
      cvc_is_employee:             input.cvc_is_employee,
      cvc_phone:                   nullIfEmpty(input.cvc_phone),

      // Client
      client_name:     nullIfEmpty(input.client_name),
      client_logo_url: nullIfEmpty(input.client_logo_url),

      // Supervision
      supervision_company:        nullIfEmpty(input.supervision_company),
      supervision_contact:        nullIfEmpty(input.supervision_contact),
      supervision_email:          nullIfEmpty(input.supervision_email),
      supervision_phone:          nullIfEmpty(input.supervision_phone),
      supervision_notifications:  input.supervision_notifications,
      supervision_attach_reports: input.supervision_attach_reports,

      // Location
      latitude:  input.latitude  ?? null,
      longitude: input.longitude ?? null,
      radius:    input.radius,

      updated_by: session.userId,
    })
    .eq('id', projectId)
    .select()
    .single()

  if (error) {
    console.error('[updateProject] DB error:', error.message)
    return { success: false, error: { _form: [error.message] } }
  }

  // Replace-all attendance_clocks:
  //   1. Delete all existing clocks for this project
  //   2. Insert the new set
  const { error: deleteError } = await supabase
    .from('attendance_clocks')
    .delete()
    .eq('project_id', projectId)

  if (deleteError) {
    console.error('[updateProject] Failed to delete old clocks:', deleteError.message)
  }

  if (clocksJson) {
    try {
      const clockIds: string[] = JSON.parse(clocksJson)
      const validClockIds = clockIds.filter((id) => id && id.trim() !== '')

      if (validClockIds.length > 0) {
        const clockRows = validClockIds.map((clockId) => ({
          project_id: projectId,
          clock_id:   clockId.trim(),
          created_by: session.userId,
        }))

        const { error: clockError } = await supabase
          .from('attendance_clocks')
          .insert(clockRows)

        if (clockError) {
          console.error('[updateProject] Failed to insert clocks:', clockError.message)
        }
      }
    } catch {
      console.error('[updateProject] Invalid attendance_clocks JSON — skipped')
    }
  }

  // Write audit log
  await writeAuditLog({
    userId:     session.userId,
    action:     'UPDATE',
    entityType: 'projects',
    entityId:   projectId,
    oldData:    oldData as Record<string, unknown>,
    newData:    data as Record<string, unknown>,
  })

  revalidatePath('/admin/projects')
  return { success: true }
}

// ---------------------------------------------------------------------------
// softDeleteProject
// ---------------------------------------------------------------------------
export async function softDeleteProject(
  id: string
): Promise<{ success: boolean; error?: string }> {
  const session = await verifySession()
  const supabase = await createClient()

  // Fetch old data for audit log (also verifies row exists)
  const { data: oldData, error: fetchError } = await supabase
    .from('projects')
    .select('*')
    .eq('id', id)
    .single()

  if (fetchError || !oldData) {
    return { success: false, error: 'הפרויקט לא נמצא או כבר נמחק' }
  }

  // Soft-delete via RPC — SECURITY DEFINER bypasses RLS on deleted_at column.
  const { data: affected, error } = await supabase.rpc('soft_delete_projects', {
    p_ids: [id],
  })

  if (error) {
    console.error('[softDeleteProject] RPC error:', error.message)
    return { success: false, error: error.message }
  }

  if (affected === 0) {
    return { success: false, error: 'הפרויקט לא נמצא או כבר נמחק' }
  }

  // Write audit log (fire-and-forget)
  await writeAuditLog({
    userId:     session.userId,
    action:     'DELETE',
    entityType: 'projects',
    entityId:   id,
    oldData:    oldData as Record<string, unknown>,
    newData:    null,
  })

  revalidatePath('/admin/projects')
  return { success: true }
}
